import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class TaskCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  project_id: string;
}

export class Task {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  due_date: string;
  @ApiProperty()
  project_id: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
